### ISSUE TITLE
[오역 수정] define-plugin.mdx

### ISSUE THREAD

**Issue by woochanleee** [line/webpack.kr#1233]
## Summary
- [ ] 오역 수정 ```define-plugin.mdx```

> Using the latter will overwrite the process object which can break compatibility with some modules that expect other values on the process object to be defined.

원문은 `latter(후자)` 가 맞긴 하나, 한글로 번역된 문장에서 헷갈릴 여지가 있어보여 `후자 -> 전자` 로 수정을 제안 해봅니다 :)

## Ref.
- https://github.com/line/webpack.kr/pull/1232

**Comment by dkstyle** [comment]
@woochanleee 
제보 주신 문장의 내용을 살펴보니 prefer `A` over `B` 를 번역하는 과정에서,
 `A`와 `B` 순서가 뒤바뀌었기 때문에 이어지는 번역에서도 말씀 주신 것 처럼 `전자`와 `후자`가 반대로 표기되어야 올바른 내용이 됩니다.

소중한 오역 제보를 해 주셔서 감사합니다. 👍 
앞서 올려주신 PR을 다시 열어 리뷰 진행하겠습니다.

**Comment by woochanleee** [comment]
감사합니다!
