### ISSUE TITLE
[마크다운 문법 수정] optimization.mdx

### ISSUE THREAD

**Issue by nlom0218** [line/webpack.kr#1364]
## Summary
- [x] 마크다운 문법 수정 ```optimization.mdx```

마크다운 문법 오류로 인해 표가 정상적으로 나타나지 않습니다.

<img width="733" alt="스크린샷 2023-09-10 오후 12 45 16" src="https://github.com/line/webpack.kr/assets/57981252/a63d5335-8f73-4ba0-a5eb-adb6713d91ad">

**Comment by dkstyle** [comment]
@nlom0218 관심과 기여에 감사드립니다. 🙏 
수정사항은 https://webpack.kr/configuration/optimization/ 에서 확인 가능합니다.

**Comment by nlom0218** [comment]
네! 감사합니다 :)
