### ISSUE TITLE
webpack-dev-server 업데이트에 따른 키값 변경

### ISSUE THREAD

**Issue by CaesiumY** [line/webpack.kr#198]
따라해보다가 막혀서 원본을 보니 업데이트 되어 있습니다.

## 기존: 

```js
+  devServer: {
+    contentBase: './dist',
+  },
```

https://webpack.kr/guides/development/#using-webpack-dev-server

## 업데이트 되어 변경된 모습

```js
+  devServer: {
+    static: './dist',
+  },
```

https://webpack.js.org/guides/development/#using-webpack-dev-server

**Comment by dkstyle** [comment]
@CaesiumY 확인 감사합니다! 👍 👍 👍 
말씀하신 내용이 최신 원문의 커밋([#5345](https://github.com/webpack/webpack.js.org/commit/81ff5e340e8b606289ee4e743d32ec4717fa0ba9))에 반영된 내용이라, 
최신 내용을 동기화 하는 PR[#197](https://github.com/line/webpack.kr/pull/197)이 머지되면서 업데이트 될 예정입니다.
