### ISSUE TITLE
[Translation] blog/2020-10-10-webpack-5-release.mdx

### ISSUE THREAD

**Issue by JEONTAK** [line/webpack.kr#376]
## Summary
- [x] Translate ```blog/2020-10-10-webpack-5-release.md```

**Comment by dkstyle** [comment]
@JEONTAK 안녕하세요, 혹시 작업 진행중이신지 확인 부탁드립니다.

**Comment by JEONTAK** [comment]
> @JEONTAK 안녕하세요, 혹시 작업 진행중이신지 확인 부탁드립니다.

@dkstyle  현재 5분의4정도 진행 했습니다!! 작업 속도가 느려서 죄송합니다 ㅠ

**Comment by dkstyle** [comment]
> > @JEONTAK 안녕하세요, 혹시 작업 진행중이신지 확인 부탁드립니다.
> 
> @dkstyle 현재 5분의4정도 진행 했습니다!! 작업 속도가 느려서 죄송합니다 ㅠ

네, 확인 감사합니다. 🙇
