### ISSUE TITLE
[Translation] guides/getting-started.md - typo fix

### ISSUE THREAD

**Issue by DavidYang2149** [line/webpack.kr#40]
## Summary
- [ ] Translate ```getting-started.md```

안녕하세요. 

webpack 한국어 번역 페이지를 잘 보고 있습니다. 😄 

글을 읽던 중 오타를 발견하여 issues를 올립니다.

[getting-started](https://webpack.kr/guides/getting-started)에서 **JavaScript**가 **JavsScript**로 표기된 것을 발견했습니다.

괜찮다면 해당 내용을 직접 수정하여 contribute하고 싶습니다.

답신을 주시면 해당 내용을 수정하여 Pull Request를 올리도록 하겠습니다.

감사합니다.

+ 오타 제보에 관련된 양식 기록이 없어서 이슈를 올바르게 올린 것인지 궁금합니다.  제목이나 내용에 수정이 필요하시다면 반영하도록 하겠습니다.

**Comment by dkstyle** [comment]
제보 감사드립니다 ! 수정 PR올려 주시면 반영하겠습니다.  😃 
Cc: @limong
