### ISSUE TITLE
[Translation] plugins/normal-module-replacement-plugin.mdx

### ISSUE THREAD

**Issue by dajeongPark-dev** [line/webpack.kr#406]
## Summary
- [x] Translate ```plugins/normal-module-replacement-plugin.md```

**Comment by dkstyle** [comment]
@dajeongPark-dev 안녕하세요, 혹시 작업 진행중이신지 확인 부탁드립니다.

**Comment by dajeongPark-dev** [comment]
> @dkstyle 

안녕하세요. 먼저 늦은 전달에 대해 죄송합니다.
번역 작업은 끝냈었는데 푸쉬가 안되어 늦어지고 있었습니다...

**Comment by dkstyle** [comment]
@dajeongPark-dev 네, 확인 감사합니다. 작업 하신 내용 PR 부탁드립니다.

**Comment by dajeongPark-dev** [comment]
@dkstyle
커밋할 때

/usr/bin/env: ‘bash’: No such file or directory
husky - pre-commit hook exited with code 127 (error)

이러한 에러가 뜨는데 해결을 못하고 있는 상황입니다.. 혹시 해결 방법에 대해 조언을 주실 수 있을까요?

**Comment by dkstyle** [comment]
@dajeongPark-dev 
혹시 Windows 환경이라면, https://github.com/typicode/husky/issues/1038 이 내용이 겪고 계신 이슈와 동일한 메시지인것으로 보이는데 한번 시도해 보시겠어요?

**Comment by dajeongPark-dev** [comment]
@dkstyle
알려주신 내용으로 문제를 잘 해결하여 풀리퀘스트했습니다.
감사합니다.
