### ISSUE TITLE
[번역] configuration/configuration-languages.mdx

### ISSUE THREAD

**Issue by kwYoohae** [line/webpack.kr#467]
configuration/configuration-languages.mdx 파일에서

**55번**라인에서 백틱안 글자를 `module`을 `모듈`로 해석하셨는데
![image](https://user-images.githubusercontent.com/74089271/142405836-efec6215-51a0-4b56-b37a-ce20c730d2ad.png)

**63**라인에서는 백틱안 글자들을  `module`이라고 해석안하셔서 궁금해서 이슈올립니다
![image](https://user-images.githubusercontent.com/74089271/142405951-6d4bc954-08f8-44cd-b1c4-26ba12daca40.png)

문맥에 대해서 수정사항인지 궁금합니다

읽어주셔서 감사합니다 😄

**Comment by dkstyle** [comment]
@kwYoohae 일반적인 문장에서 module이라고 쓰인 경우 `모듈`로 번역하지만 아래 두가지 상황에서는 `module`을 그대로 두려고 했습니다.
- 소제목에 해당하는 경우 (한글로 번역하지 않음)
- module이 webpack 설정안의 옵션 혹은 키값으로 쓰인경우

따라서 말씀주신 내용에서는 55번의 백틱안 글자가 옵션명에 해당하기 때문에 `module로 표현되는 것이 더 좋은 상황인것 같네요. 
해당 내용을 수정해 주셔도 좋을 것 같습니다 :)
