### ISSUE TITLE
맞춤법 수정 guides/hot-module-replacement.mdx

### ISSUE THREAD

**Issue by chopmozzi** [line/webpack.kr#472]
## Summary
- [x] 맞춤법 수정 ```guides/hot-module-replacement.mdx```
![hot-module-replacement](https://user-images.githubusercontent.com/44396392/142409124-37d1d08e-a44f-4584-b971-e79a274e1266.PNG)
로더가 있습니다. (그중 일부는 아래에 언급됨).
이 부분에서 해당 원문이
there are a lot of loaders out there (some of which are mentioned below) that will make hot module replacement much easier.
이 부분인데 문장안에 괄호가 있었으므로 '로더가 있습니다. (그중 일부는 아래에 언급됨.)' 혹은 '로더가 있습니다(그중 일부는 아래에 언급됨).', '로더가 있습니다. 그중 일부는 아래에 언급되었습니다.'로 수정해야할 것  같습니다.
어떤 방식으로 고치는게 좋을까요? 알려주시면 해당 부분 수정해서 PR하겠습니다.

**Comment by YukJiSoo** [comment]
@chopmozzi 
좋은 의견 감사드려요! 원문에는 문장안에 괄호로 표현되어 있지만, 읽는 사람의 입장에 보았을 때 괄호가 큰 도움을 주지 않는다고 생각해요!
개인적으로는 오히려 가독성을 떨어트리는 원인이 될 수 있다고 생각합니다.
그래서 저는 제시해주신 의견중에 `로더가 있습니다. 그중 일부는 아래에 언급되었습니다.` 로 수정되는게 자연스러울 것 같습니다.

@chopmozzi 님이 생각하실 때 읽는 사람의 입장에서 더 자연스럽게 읽혀질 것 같다는 표현으로 선택해주시면 될 것 같아요! 
적극적인 참여 감사드립니다 :)
