### ISSUE TITLE
[Translate] /guides/asset-management.mdx

### ISSUE THREAD

**Issue by yuseok** [line/webpack.kr#750]
## Summary
- [x] Translate ```guides/asset-management.mdx```

## Next guide

~~이제 [Output Management](https://webpack.js.org/guides/output-management/)로 넘어가 보겠습니다.~~
⬇
이제 [Output Management](https://webpack.kr/guides/output-management/)로 넘어가 보겠습니다.

**Comment by dkstyle** [comment]
@yuseok 확인 감사합니다.👏 👏 
링크가 영문 문서로 연결되어 있었네요. 같은 문서의 Wrapping up 쪽에 연결도 동일하게 되어있어서 함께 수정이 필요하네요. 
수정내용을, PR로 함께 부탁드려도 될까요.

**Comment by yuseok** [comment]
네 추가 확인 후 PR 요청하겠습니다😀

**Comment by yuseok** [comment]
> @yuseok 확인 감사합니다.👏 👏 링크가 영문 문서로 연결되어 있었네요. 같은 문서의 Wrapping up 쪽에 연결도 동일하게 되어있어서 함께 수정이 필요하네요. 수정내용을, PR로 함께 부탁드려도 될까요.

영문 링크가 더 있어 추가 수정하여 PR 요청 드렸습니다. #751
