### ISSUE TITLE
잘못된 번역에 대한 정정 요청 입니다.

### ISSUE THREAD

**Issue by gyutae100** [line/webpack.kr#764]
# 잘못된 번역에 대한 정정 요청 입니다.

## 내용
 - 페이지는 "https://webpack.kr/concepts/module-federation/" 입니다.
 - 페이지 내 섹션 이름은  "Low-level concepts" 입니다.
 - "Low-level concepts"섹션 내 문장 중 "2. 모듈평가(비동기)"이 잘못 번역되었습니다.
 - 영어 버전에서는 "evaluating the module (synchronous)."로 표기되어 있습니다.
 - 자세히 설명하자면, synchronous에 대한 번역이 "동기"가 아닌 "비동기"로 잘못 번역되었습니다.
 - 결론으로 번역을 "2.모듈 평가(동기)"로 변경 부탁드립니다.

**Comment by dkstyle** [comment]
@gyutae100 소중한 의견 감사합니다. 👍 👍 
최신 컨텐츠 동기화를 위한 작업 PR에 포함해서 진행하겠습니다. 
https://github.com/line/webpack.kr/pull/763/files#diff-f5421327e77821facf43962683a62b06c3099ea5657524baae0534424857c9acL48

**Comment by gyutae100** [comment]
정정 감사합니다.

해당 코멘트는 이 이슈와 직접적인 연관은 없지만, 모듈 평가가 왜 동기로 처리 하는 이유에 대해서 개인적인 추측을 추가로 적어보도록 하겠습니다.

제 추측에는, 모듈 로드는 비동기적으로 처리 되었지만, 만약 로드 된 특정 모듈을 평가하려면 특정 모듈이 의존성을 가지는 다른 모듈에 대한 로드 및 평가가 완료된 후 특정 모듈의 평가가 진행 가능하다고 봅니다.

추가적으로, 원격 모듈을 로드하는 작업은 런타임에 동적으로 진행하므로 동기적인 모듈 평가가 가능하다고 봅니다. 
동기 처리를 통해서 모듈 간 순환 의존성 처리 또는 컨테이너 중첩 또는 모듈 오버라이딩 처리가 가능하다고 봅니다.

웹팩의 한국어 번역에 기여해주신 기여자분들 덕분에 웹팩 공부 시 문제점이 되는 언어적인 허들이 많이 낮아졌습니다.
이 점에 대해서 감사합니다.

이상입니다.

**Comment by dkstyle** [comment]
@gyutae100 다시한번 좋은 의견 감사드립니다.
