### ISSUE TITLE
잘못된 번역에 대한 정정 요청 입니다.

### ISSUE THREAD

**Issue by gyutae100** [line/webpack.kr#771]
# 잘못된 번역에 대한 정정 요청 입니다.

## 내용
- 페이지는 "https://webpack.kr/plugins/split-chunks-plugin" 입니다.
- 페이지 내 섹션 헤더 이름은 "splitChunks.minChunks" 입니다.
- 섹션의 내용이 "모듈이 분할 전에 청크간에 공유되어야 하는 최소 시간입니다."로 잘못 번역되었습니다.
- 영어 버전에서는 "The minimum times must a module be shared among chunks before splitting."로 표기되어 있습니다.
- 개인적으로, "The minimum times"에 대한 번역이 "최소 시간"으로 번역되는 게 맞지 않는 것 같습니다.
- 결론으로, "최소 시간"으로 번역하는 게 옳지 않은 경우에는 "최소 시간"이 아닌 "최소 횟수" 또는 "최소 갯수"로 번역 정정 부탁드립니다.
- 감사합니다. 이상입니다.

**Comment by dkstyle** [comment]
https://github.com/line/webpack.kr/blob/kr/CONTRIBUTING_UNIVERSAL.md 내용 참고하시어, PR 부탁드리겠습니다.

**Comment by gyutae100** [comment]
지금 댓글을 확인했습니다.

오늘 내에 안내해주신 가이드대로 올리도록 하겠습니다.

감사합니다.
이상입니다.
